### ISSUE TITLE
Case sensitivity bug in gpregistrypolicydsc's GPRegistryPolicyFileParser.psm1

### ISSUE THREAD

**Issue by norbertstoll** [puppetlabs/Puppet.Dsc#140]
## Describe the Bug
Settings of gpregistrypolicydsc won't be applied because of a mismatch regarding case sensitivity. 

GPRegistryPolicyFileParser.psm1's submits a D**W**ord or Q**W**ord, while lower case (_Dword_, _Qword_) is expected.

## Expected Behavior
Values in GPRegistryPolicyFileParser.psm1 are submitted in correct case.
Affected lines are 645 and 653. 
Lines 682 and 690, too - however those didn't end up in an error within my config until now.

Corrected/Working code:

```powershell
    [System.String] GetRegTypeString()
    {
        [System.String] $result = ''

        switch ($this.ValueType)
        {
            ([RegType]::REG_SZ)
            {
                $Result = 'String'
            }
            ([RegType]::REG_EXPAND_SZ)
            {
                $Result = 'ExpandString'
            }
            ([RegType]::REG_BINARY)
            {
                $Result = 'Binary'
            }
            ([RegType]::REG_DWORD)
            {
                $Result = 'Dword' # has been $Result = 'DWord' 
            }
            ([RegType]::REG_MULTI_SZ)
            {
                $Result = 'MultiString'
            }
            ([RegType]::REG_QWORD)
            {
                $Result = 'Qword' # has been $Result = 'QWord' 
            }
            default
            {
                $Result = ''
            }
        }

        return $result
    }
```

## Steps to Reproduce
hiera-config:
```yaml
---

classes:
  include:
    - 'profile::dsc::gpregistrypolicy'

profile::dsc::gpregistrypolicy::registrypolicyfile:

  # Place-holder - Description CIS-CAT etc.
  'Registry(POL) - HKLM - \Software\Microsoft\Windows\CurrentVersion\Policies\CredUI\EnumerateAdministrators':
    dsc_valuetype: 'Dword'
    dsc_valuename: 'EnumerateAdministrators'
    dsc_valuedata: ['0']
    dsc_key: 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\CredUI'
    dsc_targettype: 'ComputerConfiguration'
```

```
PS C:\> puppet agent -t
Info: Using configured environment 'windows_test'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Error: Failed to apply catalog: Parameter dsc_valuetype failed on Dsc_registrypolicyfile[Registry(POL) - HKLM - \Software\Microsoft\Windows\CurrentVersion\Policies\CredUI\EnumerateAdministrators]: dsc_registrypolicyfile.dsc_valuetype expects an undef value or a match for Enum['Binary', 'Dword', 'ExpandString', 'MultiString', 'None', 'Qword', 'String'], got 'DWord'
PS C:\>
```

## Environment
```
mod 'puppetlabs-pwshlib', '0.8.0'
mod 'dsc-gpregistrypolicydsc', '1.2.0-0-2'
```

## Additional Context
I also puppetized the gpregistrypolicy-PowerShell Module via Puppet.Dsc (0.5.0) on my own. The mismatch remains.
